"""Adds SimulatedGatewayIntent, staff permissions, and outbox last_error field"""
# Generated by Django 5.2.14 on 2026-07-02 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulatedGatewayIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gateway_reference", models.CharField(max_length=120, unique=True)),
                ("status", models.CharField(max_length=32)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="fulfillment",
            options={
                "permissions": [
                    ("fulfill_orders", "Can drive order fulfillment"),
                    ("cancel_orders", "Can cancel orders"),
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="inventorymovement",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("adjust_inventory", "Can adjust variant stock levels")
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="refund",
            options={"permissions": [("process_refunds", "Can create refunds")]},
        ),
        migrations.RemoveConstraint(
            model_name="promotionredemption",
            name="unique_active_promotion_per_user",
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="promotionredemption",
            index=models.Index(
                fields=["promotion", "user", "released"],
                name="shop_promot_promoti_3b159e_idx",
            ),
        ),
    ]
