# Generated by Django 5.2.14 on 2026-07-02 23:33

import shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_simulatedgatewayintent_alter_fulfillment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="product-images/",
                validators=[shop.validators.validate_image_upload],
            ),
        ),
    ]
