# Generated by Django 5.2.14 on 2026-07-03 02:32

import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_address_review_wishlistitem_cart_recovery_sent_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField()),
                (
                    "secret",
                    models.CharField(
                        help_text="Used to HMAC-sign payloads.", max_length=120
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=180)),
                (
                    "event_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Subscribed event types; empty = all.",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("received", "Received"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("staff_note", models.TextField(blank=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to="shop.order",
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_requests",
                        to="shop.refund",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("method", models.CharField(max_length=80)),
                ("label", models.CharField(blank=True, max_length=120)),
                (
                    "flat_amount",
                    models.DecimalField(
                        decimal_places=2, default=shop.models.money_zero, max_digits=12
                    ),
                ),
                (
                    "free_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "min_subtotal",
                    models.DecimalField(
                        decimal_places=2, default=shop.models.money_zero, max_digits=12
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "method"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("flat_amount__gte", 0)),
                        name="shipping_rate_amount_nonnegative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.CharField(default="US", max_length=2)),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Blank matches the whole country.",
                        max_length=120,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=4, max_digits=6)),
                ("label", models.CharField(default="Sales tax", max_length=120)),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher priority wins on a tie."
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-priority", "country", "region"],
                "indexes": [
                    models.Index(
                        fields=["active", "country", "region"],
                        name="shop_taxrat_active_28330c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReturnLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="shop.orderitem",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="shop.returnrequest",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="return_line_quantity_positive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type", models.CharField(max_length=120)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("response_code", models.PositiveIntegerField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                (
                    "outbox_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_deliveries",
                        to="shop.outboxevent",
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="shop.webhookendpoint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("endpoint", "outbox_event"),
                        name="unique_webhook_delivery_per_event",
                    )
                ],
            },
        ),
    ]
