# Adds GiftCard, StoreCredit, transactions, and credit_applied checkout/order fields
# Generated by Django 5.2.14 on 2026-07-03 02:46

import django.db.models.deletion
import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_webhookendpoint_returnrequest_shippingrate_taxrate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutattempt",
            name="credit_applied",
            field=models.DecimalField(
                decimal_places=2, default=shop.models.money_zero, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="credit_applied",
            field=models.DecimalField(
                decimal_places=2, default=shop.models.money_zero, max_digits=12
            ),
        ),
        migrations.CreateModel(
            name="GiftCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=40, unique=True)),
                (
                    "initial_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("active", models.BooleanField(default=True)),
                ("issued_to_email", models.EmailField(blank=True, max_length=254)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("balance__gte", 0)),
                        name="gift_card_balance_nonnegative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoreCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=shop.models.money_zero, max_digits=12
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_credit",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("balance__gte", 0)),
                        name="store_credit_balance_nonnegative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoreCreditTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("delta", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("gift_card", "Gift card redeemed"),
                            ("checkout_hold", "Held at checkout"),
                            ("checkout_spend", "Spent on order"),
                            ("hold_release", "Hold released"),
                            ("refund_credit", "Refunded to credit"),
                            ("manual", "Manual adjustment"),
                        ],
                        max_length=30,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=180)),
                (
                    "checkout_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.checkoutattempt",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shop.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_credit_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="shop_storec_user_id_b83c43_idx",
                    )
                ],
            },
        ),
    ]
