# Generated by Django 5.2.14 on 2026-07-03 03:04

import django.db.models.deletion
import shop.models
import shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_checkoutattempt_credit_applied_order_credit_applied_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(unique=True)),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2, default=shop.models.money_zero, max_digits=12
                    ),
                ),
                (
                    "max_products",
                    models.PositiveIntegerField(
                        blank=True, help_text="Blank = unlimited.", null=True
                    ),
                ),
                (
                    "max_orders_per_month",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("features", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store_name",
                    models.CharField(default="Aster Commerce", max_length=120),
                ),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        upload_to="branding/",
                        validators=[shop.validators.validate_image_upload],
                    ),
                ),
                ("primary_color", models.CharField(default="#3b6fe6", max_length=9)),
                ("accent_color", models.CharField(default="#245c24", max_length=9)),
                ("currency", models.CharField(default="USD", max_length=3)),
            ],
            options={
                "verbose_name_plural": "store settings",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past due"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="trialing",
                        max_length=20,
                    ),
                ),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="shop.plan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
