"""Scopes active-cart uniqueness constraints to tenant plus user or session"""
# Generated by Django 5.2.14 on 2026-07-03 03:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_backfill_default_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cart",
            name="unique_active_cart_per_user",
        ),
        migrations.RemoveConstraint(
            model_name="cart",
            name="unique_active_cart_per_session",
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active"), ("user__isnull", False)),
                fields=("tenant", "user"),
                name="unique_active_cart_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_key__gt", ""), ("status", "active")),
                fields=("tenant", "session_key"),
                name="unique_active_cart_per_session",
            ),
        ),
    ]
