# Adds tenant FK to OutboxEvent and per-tenant unique coupon codes
# Generated by Django 5.2.14 on 2026-07-03 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_remove_cart_unique_active_cart_per_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxevent",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="shop.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="couponcode",
            name="normalized_code",
            field=models.CharField(db_index=True, editable=False, max_length=60),
        ),
        migrations.AddConstraint(
            model_name="couponcode",
            constraint=models.UniqueConstraint(
                fields=("tenant", "normalized_code"),
                name="unique_coupon_code_per_tenant",
            ),
        ),
    ]
