# Generated by Django 5.2.14 on 2026-07-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_backfill_outbox_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="compare_at_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original/list price for strikethrough. Display only — never charged.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="auto_apply",
            field=models.BooleanField(
                default=False,
                help_text="Apply automatically at cart (no code) when eligible.",
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="priority",
            field=models.IntegerField(
                default=0, help_text="Higher wins when several auto promos qualify."
            ),
        ),
    ]
