# Creates Invoice model for monthly tenant SaaS billing periods
# Generated by Django 5.2.14 on 2026-07-03 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_tenantmembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("plan_name", models.CharField(max_length=80)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("orders_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("paid", "Paid"),
                            ("past_due", "Past due"),
                            ("void", "Void"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="shop.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "period_start"),
                        name="unique_invoice_per_period",
                    )
                ],
            },
        ),
    ]
