"""Creates EmailSuppression model to block marketing emails to opted-out addresses"""
# Generated by Django 5.2.14 on 2026-07-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_invoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSuppression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("reason", models.CharField(default="unsubscribe", max_length=80)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
