"""Renames payment and catalog indexes; adds EmailDelivery sending status."""
# Generated by Django 5.2.15 on 2026-07-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0023_round4_constraints"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="shop_produc_slug_76971b_idx",
        ),
        migrations.RenameIndex(
            model_name="idempotencyrecord",
            new_name="shop_idempo_expires_330678_idx",
            old_name="shop_idempo_expires_idx",
        ),
        migrations.RenameIndex(
            model_name="payment",
            new_name="shop_paymen_tenant__6a03f0_idx",
            old_name="shop_payment_tenant_status_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentevent",
            new_name="shop_paymen_tenant__c8efd9_idx",
            old_name="shop_payevent_tenant_created_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="shop_produc_tenant__113447_idx",
            old_name="shop_product_tenant_status_feat_idx",
        ),
        migrations.RenameIndex(
            model_name="storecredittransaction",
            new_name="shop_storec_tenant__5c6977_idx",
            old_name="shop_sctx_tenant_created_idx",
        ),
        migrations.AlterField(
            model_name="emaildelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                default="queued",
                max_length=20,
            ),
        ),
    ]
