# Generated by Django 5.2.15 on 2026-07-14 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0025_round5_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundGatewayEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(db_index=True, max_length=32)),
                (
                    "provider_event_id",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                ("event_type", models.CharField(blank=True, max_length=80)),
                (
                    "gateway_reference",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("signature", models.CharField(blank=True, max_length=256)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=20,
                    ),
                ),
                ("processing_result", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="provider",
            field=models.CharField(db_index=True, default="simulated", max_length=32),
        ),
        migrations.AddField(
            model_name="paymentevent",
            name="provider",
            field=models.CharField(db_index=True, default="simulated", max_length=32),
        ),
        migrations.AddField(
            model_name="paymentevent",
            name="provider_event_id",
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AddField(
            model_name="refund",
            name="gateway_reference",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name="paymentevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_event_id", ""), _negated=True),
                fields=("tenant", "provider", "provider_event_id"),
                name="unique_payment_event_per_provider",
            ),
        ),
        migrations.AddField(
            model_name="inboundgatewayevent",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shop.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="inboundgatewayevent",
            index=models.Index(
                fields=["provider", "status", "created_at"],
                name="shop_inboun_provide_bddb15_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundgatewayevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_event_id", ""), _negated=True),
                fields=("provider", "provider_event_id"),
                name="unique_inbound_gateway_event",
            ),
        ),
    ]
